name: CI  # Название воркфлоу, отображаемое в интерфейсе GitHub Actions.

on:  # Определяет условия запуска воркфлоу.
  push:  # Воркфлоу запускается при событии push в репозиторий.
    branches:  # Определяет ветки, на которых будет запускаться воркфлоу.
      - main  # Воркфлоу запускается только при push в ветку main.

jobs:  # Определяет список заданий, которые будут выполняться в рамках воркфлоу.
  build:  # Имя задания, можно выбрать произвольное.
    runs-on: ubuntu-latest  # Определяет операционную систему, на которой будет выполняться задание. В данном случае, используется последняя версия Ubuntu.

    steps:  # Список шагов, которые нужно выполнить в рамках задания.
      - name: Checkout repository  # Название шага.
        uses: actions/setup-node@v3  # Использует действие для клонирования репозитория.

      - name: Setup Node.js with cache  # Название шага.
        uses: actions/setup-node@v3  # Использует действие для установки Node.js.
        with:  # Параметры для действия.
          node-version: '14'  # Устанавливает версию Node.js.
          cache: 'npm'  # Включает кеширование для npm.

      - name: Install dependencies  # Название шага.
        run: make install  # Выполняет команду `make install` для установки зависимостей.

      - name: Build project  # Название шага.
        run: make build  # Выполняет команду `make build` для сборки проекта.

      - name: Run tests  # Название шага.
        run: make test  # Выполняет команду `make test` для запуска тестов.

      - name: Run linter  # Название шага.
        run: make lint  # Выполняет команду `make lint` для запуска линтера.

      # Этот шаг используется для проверки уязвимостей в зависимостях проекта
      # и выполняется с использованием инструмента Snyk.
      # Предполагается, что переменная среды SNYK_TOKEN содержит токен для авторизации.
      - name: Run Snyk to check for vulnerabilities  # Название шага.
        uses: snyk/actions/node@master  # Использует действие для проверки уязвимостей.
        env:  # Определяет переменные среды, необходимые для выполнения действия.
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}  # Использует токен Snyk для авторизации.
